# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07630f2bfb37f3f6c93f5dee1caf20864694c8ce3e4cf3577d8153934fbcf0a07ca186a721c34ed59bde8fa5a0b483446e0ae97089dd6b55bbc98b362329e125

test:
  secret_key_base: 5a5d07f06301f20053613c666598e3748a96fefd7e25ef96ec3f60fe9c6e28e952b0bcdae0bbe6faa67b1a95052902b12ff4a4520015b9284313fe7baa639abb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
